#!/bin/sh
USER=root
HOST=f.78997899.xyz
DIR=/www/xray_web/   # the directory where your web site files should go

git add -A
git commit -m "auto update"
git push

hugo && rsync -avz --delete public/ ${USER}@${HOST}:${DIR}

exit 0
